<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Список сайтов</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 60px;
        }
        footer.footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
            line-height: 60px;
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>

<?php
/**
 * @var $urls
 * */
?>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Анализатор страницы</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main role="main" class="container">
    <h1>Список сайтов</h1>
    <table class="table" data-test="urls">
        <thead>
        <tr>
            <th>ID</th>
            <th>Название сайта</th>
            <th>Дата создания</th>
            <th>Дата последней проверки</th>
            <th>Код последней проверки</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($urls as $url): ?>
            <tr data-test="url">
                <td><?= $url->id ?></td>
                <td><a href="/urls/<?= $url->id ?>"><?= $url->name ?></a></td>
                <td><?= $url->created_at ?></td>
                <td><?= $url->lastCheckDate ?? 'Нет данных' ?></td>
                <td><?= $url->status_code ?? 'Нет данных' ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</main>

<footer class="footer">
    <div class="container">
        <span class="text-muted">© 2023 Анализатор страницы</span>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
